//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSFilterShim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSFilterShim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string AlphaChannelName {
            get {
                return ResourceManager.GetString("AlphaChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameters..
        /// </summary>
        internal static string BadParameters {
            get {
                return ResourceManager.GetString("BadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string BlueChannelName {
            get {
                return ResourceManager.GetString("BlueChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        internal static string ConfigDialog_FilterSearchBox_BackText {
            get {
                return ResourceManager.GetString("ConfigDialog_FilterSearchBox_BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk full..
        /// </summary>
        internal static string DiskFullError {
            get {
                return ResourceManager.GetString("DiskFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Paint.NET plug-in does not support colBytes other than 1..
        /// </summary>
        internal static string errHostDoesNotSupportColStep {
            get {
                return ResourceManager.GetString("errHostDoesNotSupportColStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires services not provided by this Paint.NET plug-in..
        /// </summary>
        internal static string errPlugInHostInsufficient {
            get {
                return ResourceManager.GetString("errPlugInHostInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A requested property could not be found..
        /// </summary>
        internal static string errPlugInPropertyUndefined {
            get {
                return ResourceManager.GetString("errPlugInPropertyUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File I/O error..
        /// </summary>
        internal static string FileIOError {
            get {
                return ResourceManager.GetString("FileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File open error..
        /// </summary>
        internal static string FileOpenError {
            get {
                return ResourceManager.GetString("FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read error..
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File write error..
        /// </summary>
        internal static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string GreenChannelName {
            get {
                return ResourceManager.GetString("GreenChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Height must be less than or equal to 32000 pixels..
        /// </summary>
        internal static string ImageHeightTooLarge {
            get {
                return ResourceManager.GetString("ImageHeightTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size must be less than or equal to 32000x32000 pixels..
        /// </summary>
        internal static string ImageSizeTooLarge {
            get {
                return ResourceManager.GetString("ImageSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Width must be less than or equal to 32000 pixels..
        /// </summary>
        internal static string ImageWidthTooLarge {
            get {
                return ResourceManager.GetString("ImageWidthTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PiPl version in {0}: {1},  Expected version 0..
        /// </summary>
        internal static string InvalidPiPLVersionFormat {
            get {
                return ResourceManager.GetString("InvalidPiPLVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sample point..
        /// </summary>
        internal static string InvalidSamplePoint {
            get {
                return ResourceManager.GetString("InvalidSamplePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null handle error..
        /// </summary>
        internal static string NullHandleError {
            get {
                return ResourceManager.GetString("NullHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory..
        /// </summary>
        internal static string OutOfMemoryError {
            get {
                return ResourceManager.GetString("OutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string RedChannelName {
            get {
                return ResourceManager.GetString("RedChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image mode..
        /// </summary>
        internal static string UnsupportedImageMode {
            get {
                return ResourceManager.GetString("UnsupportedImageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User canceled.
        /// </summary>
        internal static string UserCanceledError {
            get {
                return ResourceManager.GetString("UserCanceledError", resourceCulture);
            }
        }
    }
}
