//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSFilterPdn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSFilterPdn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string AlphaChannelName {
            get {
                return ResourceManager.GetString("AlphaChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameters..
        /// </summary>
        internal static string BadParameters {
            get {
                return ResourceManager.GetString("BadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter does not support processing empty layers..
        /// </summary>
        internal static string BlankDataNotSupported {
            get {
                return ResourceManager.GetString("BlankDataNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string BlueChannelName {
            get {
                return ResourceManager.GetString("BlueChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string ConfigDialog_addDirBtn_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_addDirBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConfigDialog_buttonCancel_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_buttonCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ConfigDialog_buttonOK_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_buttonOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string ConfigDialog_dirHeader_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_dirHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Directories.
        /// </summary>
        internal static string ConfigDialog_dirTab_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_dirTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        internal static string ConfigDialog_FilterSearchBox_BackText {
            get {
                return ResourceManager.GetString("ConfigDialog_FilterSearchBox_BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string ConfigDialog_filterTab_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_filterTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder load progress:.
        /// </summary>
        internal static string ConfigDialog_fldrLoadProgLbl_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_fldrLoadProgLbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} of {1}).
        /// </summary>
        internal static string ConfigDialog_FolderCount_Format {
            get {
                return ResourceManager.GetString("ConfigDialog_FolderCount_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string ConfigDialog_FolderName_Format {
            get {
                return ResourceManager.GetString("ConfigDialog_FolderName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ConfigDialog_remDirBtn_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_remDirBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Filter.
        /// </summary>
        internal static string ConfigDialog_runFilterBtn_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_runFilterBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show About box.
        /// </summary>
        internal static string ConfigDialog_showAboutBoxcb_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_showAboutBoxcb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Subdirectories.
        /// </summary>
        internal static string ConfigDialog_subDirSearchCb_Text {
            get {
                return ResourceManager.GetString("ConfigDialog_subDirSearchCb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk full..
        /// </summary>
        internal static string DiskFullError {
            get {
                return ResourceManager.GetString("DiskFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File I/O error..
        /// </summary>
        internal static string FileIOError {
            get {
                return ResourceManager.GetString("FileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File open error..
        /// </summary>
        internal static string FileOpenError {
            get {
                return ResourceManager.GetString("FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read error..
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File write error..
        /// </summary>
        internal static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string GreenChannelName {
            get {
                return ResourceManager.GetString("GreenChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Paint.NET plug-in does not support colBytes other than 1..
        /// </summary>
        internal static string HostDoesNotSupportColStep {
            get {
                return ResourceManager.GetString("HostDoesNotSupportColStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height must be less than or equal to 32000 pixels..
        /// </summary>
        internal static string ImageHeightTooLarge {
            get {
                return ResourceManager.GetString("ImageHeightTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less than or equal to 32000x32000 pixels..
        /// </summary>
        internal static string ImageSizeTooLarge {
            get {
                return ResourceManager.GetString("ImageSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width must be less than or equal to 32000 pixels..
        /// </summary>
        internal static string ImageWidthTooLarge {
            get {
                return ResourceManager.GetString("ImageWidthTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sample point..
        /// </summary>
        internal static string InvalidSamplePoint {
            get {
                return ResourceManager.GetString("InvalidSamplePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mask.
        /// </summary>
        internal static string MaskChannelName {
            get {
                return ResourceManager.GetString("MaskChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null handle error..
        /// </summary>
        internal static string NullHandleError {
            get {
                return ResourceManager.GetString("NullHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory..
        /// </summary>
        internal static string OutOfMemoryError {
            get {
                return ResourceManager.GetString("OutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string PiMIDefaultCategoryName {
            get {
                return ResourceManager.GetString("PiMIDefaultCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an entry point named &apos;{0}&apos; in  &apos;{1}&apos;.
        /// </summary>
        internal static string PluginEntryPointNotFound {
            get {
                return ResourceManager.GetString("PluginEntryPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires services not provided by this Paint.NET plug-in..
        /// </summary>
        internal static string PlugInHostInsufficient {
            get {
                return ResourceManager.GetString("PlugInHostInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A requested property could not be found..
        /// </summary>
        internal static string PlugInPropertyUndefined {
            get {
                return ResourceManager.GetString("PlugInPropertyUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSFilterShim.exe is not in the Effects folder..
        /// </summary>
        internal static string PSFilterShimNotFound {
            get {
                return ResourceManager.GetString("PSFilterShimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string RedChannelName {
            get {
                return ResourceManager.GetString("RedChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown port..
        /// </summary>
        internal static string UnknownChannelPort {
            get {
                return ResourceManager.GetString("UnknownChannelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error code: {0}.
        /// </summary>
        internal static string UnknownErrorCodeFormat {
            get {
                return ResourceManager.GetString("UnknownErrorCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported bit offset..
        /// </summary>
        internal static string UnsupportedChannelBitOffset {
            get {
                return ResourceManager.GetString("UnsupportedChannelBitOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported column bits..
        /// </summary>
        internal static string UnsupportedChannelColumnBits {
            get {
                return ResourceManager.GetString("UnsupportedChannelColumnBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported depth..
        /// </summary>
        internal static string UnsupportedChannelDepth {
            get {
                return ResourceManager.GetString("UnsupportedChannelDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported depth conversion..
        /// </summary>
        internal static string UnsupportedChannelDepthConversion {
            get {
                return ResourceManager.GetString("UnsupportedChannelDepthConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported row bits..
        /// </summary>
        internal static string UnsupportedChannelRowBits {
            get {
                return ResourceManager.GetString("UnsupportedChannelRowBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image mode..
        /// </summary>
        internal static string UnsupportedImageMode {
            get {
                return ResourceManager.GetString("UnsupportedImageMode", resourceCulture);
            }
        }
    }
}
